# Generated by Django 4.2 on 2023-04-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_player', '0002_video_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
